name: Deploy App to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: |
          docker build -t app-deploy-demo .
          docker run -d -p 80:80 app-deploy-demo
